framework:
    secret: "secret"
    test: ~
    router:
        resource: "%kernel.root_dir%/routing.yml"

security:
    providers:
        in_memory:
            memory: ~
    firewalls:
        default:
            anonymous: ~

tekoway_rollbar:
    access_token: '12345678912345678912345678912345'